const healthemojis = [
  "<:health_0:1278757291646259232>",
  "<:health0:1278757283790323854>",
  "<:health1:1278757275942780968>",
  "<:health2:1278757268774457376>",
  "<:health3:1278757260843028551>",
  "<:health4:1278757251535863862>",
  "<:health5:1278757242786545767>",
  "<:health6:1278757232959426592>",
  "<:health7:1278757222469472339>",
  "<:health8:1278757213057323164>",
  "<:health9:1278757200176873544>",
  "<:health10:1293308044167483545>",
  "<:health11:1293308058138841290>",
  "<:health12:1293308069404606464>",
  "<:health13:1293308089381949480>",
  "<:health14:1293308105555316837>",
  "<:health15:1293308124144341033>",
];

const dmgemojis = [
  "<:attack__3:1308565301226377348>",
  "<:attack_3:1308565243768733696>",
  "<:attack_2:1308565231236157470>",
  "<:attack_1:1308565220930617425>",
  "<:attack0:1278757419488383090>",
  "<:attack1:1278757410290405522>",
  "<:attack2:1278757401511858287>",
  "<:attack3:1278757393563389995>",
  "<:attack4:1278757385405730846>",
  "<:attack5:1278757377222639616>",
  "<:attack6:1278757369819562036>",
  "<:attack7:1278757359606435922>",
  "<:attack8:1278757344066666517>",
  "<:attack9:1278757315373306009>",
  "<:attack10:1278757304027844731>",
];

const raritysymbols = ["*️⃣", "✳️", "⚛️", "<:master:1325987682941145259>"];

const raritycolors = [0x3b88c3, 0x77b255, 0x9266cc, 0xec9603];

const raritynames = ["Common", "Rare", "Special", "Master"];

const classes = [
  {
    id: 0,
    name: "Healing",
    emoji: "<:healing:1326216242683711560>",
    legendary: 51,
  },
  {
    id: 1,
    name: "Damaging",
    emoji: "<:damaging:1326215155339493488>",
    legendary: 53,
  },
  {
    id: 2,
    name: "Defense",
    emoji: "<:defense:1326215162939576320>",
    legendary: 60,
  },
  {
    id: 3,
    name: "Summoning",
    emoji: "<:summoning:1326215191234351188>",
    legendary: 61,
  },
  {
    id: 4,
    name: "Movement",
    emoji: "<:movement:1326215169973682230>",
    legendary: 82,
  },
  {
    id: 5,
    name: "Transformation",
    emoji: "<:transformation:1326215197131669639>",
    legendary: 57,
  },
  {
    id: 6,
    name: "Shuffling",
    emoji: "<:1f500:1397251831159062739>",
    legendary: 47,
  },
  {
    id: 7,
    name: "Musical",
    emoji: "<:musical:1326215176294236212>",
    legendary: 63,
  },
  {
    id: 8,
    name: "Teamup",
    emoji: "<:teamup:1396899478069317712>",
    legendary: 95,
  },
];

const devotionhelp =
  'At any time through `/dojo` you have the ability to 🛐 **Devote** any amount of Emojis to the art of their class, permanently losing them in exchange for **"devotion points"** correlated to their rarity. You can view your devotion progress at any time by running `/devotions`.\n\nWhen you collect a total of **40** devotion points for a single class, you will be awarded the <:master:1325987682941145259> **Master** of that class to be used in your own Squad. The bar will roll back to 0, and you are able to get more of the same <:master:1325987682941145259> **Master**s. These <:master:1325987682941145259> **Master** Emojis are quite powerful, synergizing with their class like no other Emoji can.';

const emojis = [
  {
    emoji: "👏",
    id: 0,
    hp: 4,
    dmg: 0,
    rarity: 0,
    names: ["Clap", "Clapping", "Clapping Hands", "Boi", "Spades"],
    class: 8,
    description: "Deals 1 more damage for each undefeated friendly 👏",
  },
  {
    emoji: "😘",
    id: 1,
    hp: 3,
    dmg: 1,
    rarity: 1,
    names: [
      "Kissing Heart",
      "Kiss",
      "Kissing",
      "Mwah",
      "Girlfriend",
      "Gf",
      "Boyfriend",
      "Bf",
      "Partner",
      "Hearts",
    ],
    class: 0,
    description:
      "When the friendly Emoji in front of this is attacked for more than 1 damage, heals it by 1",
  },
  {
    emoji: "😌",
    id: 2,
    hp: 3,
    dmg: 2,
    rarity: 0,
    names: ["Relieved", "Calm", "Relaxed", "Clubs"],
    class: 2,
    description: "Takes 1 less damage from every attack, to a minimum of 1",
  },
  {
    emoji: "😰",
    id: 3,
    hp: 6,
    dmg: 1,
    rarity: 0,
    names: [
      "Cold Sweat",
      "Worry",
      "Worried",
      "Cold",
      "Horrified",
      "Horror",
      "Mortified",
      "Scared",
      "Sweating",
      "Sweat",
    ],
    class: 4,
    description:
      "When attacked, switches places with the friendly Emoji behind it",
  },
  {
    emoji: "😀",
    id: 4,
    hp: 5,
    dmg: 3,
    rarity: 0,
    names: [
      "Grinning",
      "Grinning Face",
      "Grin",
      "Smiling",
      "Smiling Face",
      "Smile",
      "Happy",
      "Happy Face",
      "Swords",
    ],
    class: 1,
    description: "Nothing special",
  },
  {
    emoji: "🐢",
    id: 5,
    hp: 5,
    dmg: 1,
    rarity: 1,
    names: ["Turtle", "Tortoise"],
    class: 4,
    description:
      "When attacked, moves to the back of your Squad and Heals itself by 1",
  },
  {
    emoji: "🗣️",
    id: 6,
    hp: 4,
    dmg: 2,
    rarity: 2,
    names: ["Speaking Head", "Speaking", "Facts", "Spitting", "Shout"],
    class: 5,
    description:
      "When attacking at more than 2 health, lowers the enemy Emoji's attack power by 1 to a minimum of 0",
  },
  {
    emoji: "😶",
    id: 7,
    hp: 1,
    dmg: 0,
    rarity: -1,
    names: ["No Mouth", "Blank", "Petrified"],
    description: "Nothing special (spooked by 👻)",
  },
  {
    emoji: "🤝",
    id: 8,
    hp: 3,
    dmg: 1,
    rarity: 1,
    names: ["Handshake", "Hand Shake", "Shake", "Hands", "Hand", "Jacks"],
    class: 8,
    description:
      "Will also attack if there is one friendly Emoji in front of it",
  },
  {
    emoji: "🎓",
    id: 9,
    hp: 1,
    dmg: 0,
    rarity: 1,
    names: [
      "Mortar Board",
      "Graduation Hat",
      "Grad Hat",
      "Graduation Cap",
      "Grad Cap",
    ],
    class: 3,
    description:
      "When attacked or defeated, summons three 👏 with 1 health and one attack value and defeats itself",
  },
  {
    emoji: "🔀",
    id: 10,
    hp: 1,
    dmg: 0,
    rarity: 0,
    names: ["Twisted Rightwards Arrows", "Shuffle", "Shuffle Button", "TRWA"],
    class: 6,
    description:
      "When attacked or defeated, Shuffles the enemy Squad and defeats itself",
  },
  {
    emoji: "🪦",
    id: 11,
    hp: 1,
    dmg: 2,
    rarity: 1,
    names: ["Headstone", "Grave", "Gravestone", "Tombstone", "Tomb", "Sprouts"],
    class: 0,
    description: "When a friendly Emoji is defeated, heals itself by 1",
  },
  {
    emoji: "🥋",
    id: 12,
    hp: 2,
    dmg: 2,
    rarity: 0,
    names: ["Martial Arts Uniform", "Gi", "Kung Fu", "Kungfu", "Kung-fu"],
    class: 8,
    description:
      "The friendly Emoji in front of this attacks for 1 more damage",
  },
  {
    emoji: "🎸",
    id: 13,
    hp: 4,
    dmg: 2,
    rarity: 0,
    names: ["Guitar", "Electric Guitar", "Rock and Roll"],
    class: 7,
    description:
      "If there is at least one undefeated friendly 🎶, deal 1 more damage",
  },
  {
    emoji: "🎶",
    id: 14,
    hp: 1,
    dmg: 1,
    rarity: 0,
    names: [
      "Notes",
      "Music",
      "Musical Notes",
      "Music Notes",
      "Music Note",
      "Melody",
      "Beat",
    ],
    class: 7,
    description:
      "Nothing special (makes many music-related Emojis more powerful)",
  },
  {
    emoji: "🎣",
    id: 15,
    hp: 3,
    dmg: 1,
    rarity: 0,
    names: [
      "Fishing Pole And Fish",
      "Fishing Pole",
      "Fishing Rod",
      "Rod",
      "Fish",
      "Fisher",
      "Fisherman",
      "Angler",
    ],
    class: 4,
    description:
      "When attacked, moves the furthermost enemy emoji to the front of the enemy Squad",
  },
  {
    emoji: "⛳",
    id: 16,
    hp: 3,
    dmg: 1,
    rarity: 0,
    names: ["Golf", "Hole in one", "Putt", "Drive"],
    class: 4,
    description:
      "When attacked, moves the frontmost enemy emoji to the back of the enemy Squad",
  },
  {
    emoji: "🛡️",
    id: 17,
    hp: 4,
    dmg: 2,
    rarity: 1,
    names: ["Shield", "Guard", "Ward", "Houses"],
    class: 2,
    description:
      "Takes 1 less damage for every friendly undefeated Defense class emoji, to a minimum of 1. Cannot be healed",
  },
  {
    emoji: "💀",
    id: 18,
    hp: 1,
    dmg: 2,
    rarity: 1,
    names: ["Skull", "Dead", "Death", "Diamonds"],
    class: 0,
    description: "When an enemy Emoji is defeated, heals itself by 1",
  },
  {
    emoji: "🥴",
    id: 19,
    hp: 4,
    dmg: 2,
    rarity: 1,
    names: ["Woozy Face", "Woozy", "Drunk", "Tipsy", "Octothorpe"],
    class: 6,
    description: "When your Squad is Shuffled, heals itself by 1",
  },
  {
    emoji: "♟️",
    id: 20,
    hp: 1,
    dmg: 2,
    rarity: 0,
    names: ["Chess Pawn", "Pawn"],
    class: 5,
    description: "When this defeats an Emoji, it becomes a 👑",
  },
  {
    emoji: "👑",
    id: 21,
    hp: 8,
    dmg: 3,
    rarity: -1,
    names: ["Crown", "Royalty", "Royal", "Queen", "King"],
    description: "Nothing special (starts as ♟️)",
  },
  {
    emoji: "😡",
    id: 22,
    hp: 3,
    dmg: 0,
    rarity: 0,
    names: ["Rage", "Angry", "Mad", "Fury", "Furious", "Enraged"],
    class: 1,
    description:
      "Attacks for half the number of undefeated enemy Emojis (rounded up), plus its attack power",
  },
  {
    emoji: "🦎",
    id: 23,
    hp: 3,
    dmg: 1,
    rarity: 0,
    names: ["Lizard", "Gecko"],
    class: 5,
    description: "If this is the only undefeated friendly Emoji, become a 🐲",
  },
  {
    emoji: "🐲",
    id: 24,
    hp: 6,
    dmg: 5,
    rarity: -1,
    names: ["Dragon Face", "Dragon", "Big Lizard", "Lizard Crown"],
    description: "Nothing special (starts as 🦎)",
  },
  {
    emoji: "☠️",
    id: 25,
    hp: 3,
    dmg: 1,
    rarity: 2,
    names: [
      "Skull Crossbones",
      "Skull and Crossbones",
      "Jolly Roger",
      "Crossbones",
    ],
    class: 0,
    description:
      "When an enemy Emoji is defeated, heals the friendly Emoji behind it by 1",
  },
  {
    emoji: "🍒",
    id: 26,
    hp: 2,
    dmg: 1,
    rarity: 1,
    names: ["Cherries", "Cherry"],
    class: 3,
    description: "At the beginning of the Battle, doubles itself",
  },
  {
    emoji: "🌀",
    id: 27,
    hp: 4,
    dmg: 1,
    rarity: 1,
    names: ["Cyclone", "Spiral", "Portal", "Black Hole"],
    class: 6,
    description:
      "When your Squad is Shuffled, Shuffles the enemy Squad and defeats itself (Only one takes effect if multiple are undefeated)",
  },
  {
    emoji: "🛻",
    id: 28,
    hp: 3,
    dmg: 3,
    rarity: 1,
    names: ["Pickup Truck", "Truck", "Pickup"],
    class: 4,
    description: "When your Squad is Shuffled, moves to the back",
  },
  {
    emoji: "🚏",
    id: 29,
    hp: 1,
    dmg: 2,
    rarity: 1,
    names: ["Busstop", "Bus Stop"],
    class: 0,
    description:
      "When your Squad is Shuffled, heals the Emoji behind itself by 2",
  },
  {
    emoji: "🚌",
    id: 30,
    hp: 4,
    dmg: 4,
    rarity: 2,
    names: ["Bus", "Trolley", "Tram", "Train"],
    class: 4,
    description:
      "When your Squad is Shuffled, heals itself by 2, and there is at least one undefeated friendly 🚏, moves behind it",
  },
  {
    emoji: "🍿",
    id: 31,
    hp: 4,
    dmg: 2,
    rarity: 1,
    names: ["Popcorn", "Pop", "Corn", "Kings"],
    class: 0,
    description:
      "When your Squad is Shuffled, heals the frontmost friendly Emoji by 2",
  },
  {
    emoji: "🧊",
    id: 32,
    hp: 3,
    dmg: 2,
    rarity: 2,
    names: ["Ice Cube", "Ice", "Cold", "Frozen"],
    class: 6,
    description: "While undefeated, your squad cannot be Shuffled",
  },
  {
    emoji: "💨",
    id: 33,
    hp: 1,
    dmg: 1,
    rarity: 0,
    names: ["Dash", "Puff of Smoke", "Poof", "Gust of Wind", "Gust", "Wind"],
    class: 0,
    description:
      "Before your Squad is Shuffled, heals the frontmost friendly Emoji by 2",
  },
  {
    emoji: "⚡",
    id: 34,
    hp: 2,
    dmg: 2,
    rarity: 2,
    names: [
      "Zap",
      "Lightning",
      "Lightning Bolt",
      "Thunder",
      "Thunder Bolt",
      "Acdc",
    ],
    class: 1,
    description: "Attacks the 2 frontmost enemy emojis at once",
  },
  {
    emoji: "🧱",
    id: 35,
    hp: 2,
    dmg: 1,
    rarity: 1,
    names: ["Bricks", "Brick"],
    class: 2,
    description:
      "Takes 2 less damage from every attack, to a minimum of 1. Cannot be healed",
  },
  {
    emoji: "💣",
    id: 36,
    hp: 1,
    dmg: 0,
    rarity: 1,
    names: ["Bomb", "Explode", "Explosion"],
    class: 1,
    description:
      "When attacked or defeated, defeats the frontmost enemy emoji and defeats itself",
  },
  {
    emoji: "👻",
    id: 37,
    hp: 4,
    dmg: 1,
    rarity: 2,
    names: ["Ghost", "Spectre", "Haunt", "Petrify"],
    class: 5,
    description:
      "Every other round when attacking, transforms the frontmost enemy Emoji into a 😶 with identical stats",
  },
  {
    emoji: "✨",
    id: 38,
    hp: 3,
    dmg: -1,
    rarity: -1,
    names: [
      "Sparkles",
      "Sparkle",
      "Stardust",
      "Twinkles",
      "Twinkle",
      "Glitter",
    ],
    description: "After attacking, damages itself by 1 (scattered by 🦄)",
  },
  {
    emoji: "🦄",
    id: 39,
    hp: 3,
    dmg: 2,
    rarity: 2,
    names: ["Unicorn", "Magic Horse", "Pegasus", "Pony"],
    class: 3,
    description: "When defeated, summons ✨ at the front of the enemy Squad",
  },
  {
    emoji: "🃏",
    id: 40,
    hp: 6,
    dmg: 2,
    rarity: 0,
    names: ["Black Joker", "Joker", "Joker Card", "Jimbo"],
    class: 2,
    description: "Increases any damage taken to itself by 1",
  },
  {
    emoji: "🌪️",
    id: 41,
    hp: 3,
    dmg: 1,
    rarity: 1,
    names: ["Cloud Tornado", "Tornado", "Hurricane"],
    class: 6,
    description: "When attacked or defeated, Shuffles the enemy Squad",
  },
  {
    emoji: "💃",
    id: 42,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: [
      "Dancer",
      "Dancing Woman",
      "Dance",
      "Salsa",
      "Salsa Dancer",
      "Tango",
      "Tango Dancer",
      "Acorns",
    ],
    class: 4,
    description:
      "After attacking, switches places with the friendly Emoji behind it",
  },
  {
    emoji: "🪅",
    id: 43,
    hp: 4,
    dmg: 1,
    rarity: 1,
    names: ["Piñata", "Pinata", "Llama", "Candy", "Birthday", "Birthday Party"],
    class: 2,
    description:
      "When defeated, heals the new frontmost friendly Emoji by 2 and damages the frontmost enemy Emoji by 2",
  },
  {
    emoji: "🎻",
    id: 44,
    hp: 2,
    dmg: 2,
    rarity: 0,
    names: ["Violin", "Cello", "Acoustic", "Acoustic Guitar"],
    class: 7,
    description:
      "If there is at least one undefeated friendly 🎶, deal 3 more damage",
  },
  {
    emoji: "📻",
    id: 45,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: [
      "Radio",
      "Fm",
      "Am",
      "Station",
      "Radio Station",
      "Broadcast",
      "Radio Broadcast",
    ],
    class: 7,
    description: "When defeated, summons 🎶 at the back of your Squad",
  },
  {
    emoji: "🔥",
    id: 46,
    hp: 3,
    dmg: 3,
    rarity: 1,
    names: ["Fire", "Flame", "Flames", "Heat"],
    class: 1,
    description:
      "When this Emoji is defeated, damages the new frontmost friendly Emoji by 2",
  },
  {
    emoji: "🌋",
    id: 47,
    hp: 4,
    dmg: 2,
    rarity: 3, // Master of Shuffling
    names: [
      "Volcano",
      "Krakatoa",
      "Eruption",
      "Erupt",
      "Lava",
      "Wildfire",
      "Wild Fire",
      "Wildfires",
      "Wild Fires",
    ],
    class: 6,
    description:
      "When your Squad is Shuffled, summon 🔥 at the front of the enemy team with 1 health and 1 attack power",
  },
  {
    emoji: "🎉",
    id: 48,
    hp: 2,
    dmg: 1,
    rarity: 2,
    names: [
      "Tada",
      "Party Popper",
      "Party Horn",
      "Popper",
      "Confetti",
      "Horn",
      "Celebration",
    ],
    class: 0,
    description:
      "When an enemy Emoji is defeated and this is at the back of the Squad, heals the frontmost friendly Emoji for 1",
  },
  {
    emoji: "🥏",
    id: 49,
    hp: 6,
    dmg: 3,
    rarity: 2,
    names: ["Flying Disc", "Disc", "Frisbee"],
    class: 1,
    description: "Attacks the Emoji behind this for 1 when attacking",
  },
  {
    emoji: "⏭️",
    id: 50,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: [
      "Track Next",
      "Next Track",
      "Next Track Button",
      "Next",
      "Skip",
      "Skip Button",
      "Track Skip",
      "Skip Track",
      "Skip Track Button",
    ],
    class: 6,
    description: "When healed, Shuffles your Squad",
  },
  {
    emoji: "🩻",
    id: 51,
    hp: 1,
    dmg: 2,
    rarity: 3, // Master of Healing
    names: ["X Ray", "X-ray", "Xray", "Scan", "Mri"],
    class: 0,
    description:
      "When a friendly Emoji is defeated, heals all friendly Emojis behind itself by 1",
  },
  {
    emoji: "🌃",
    id: 52,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: [
      "Night with Stars",
      "Night",
      "Nighttime",
      "Night in City",
      "Stars",
      "Star",
      "Starry",
      "Starry Night",
      "Dark City",
      "Night City",
      "City Night",
    ],
    class: 1,
    description:
      "When this defeats an Emoji, hurts all enemy copies of it by 1",
  },
  {
    emoji: "🐺",
    id: 53,
    hp: 4,
    dmg: 3,
    rarity: 3, // Master of Damaging
    names: ["Wolf", "Predator"],
    class: 1,
    description:
      "When this defeats an Emoji, heals itself by 1 and increases its attack power by 1",
  },
  {
    emoji: "🫧",
    id: 54,
    hp: 2,
    dmg: 2,
    rarity: 1,
    names: ["Bubbles", "Bubble"],
    class: 2,
    description: "Reduces any damage taken to itself to 1. Cannot be healed",
  },
  {
    emoji: "🍌",
    id: 55,
    hp: 2,
    dmg: 2,
    rarity: 1,
    names: ["Banana", "Banana Peel", "Slippery", "Slip"],
    class: 4,
    description:
      "When defeated, damages the frontmost enemy Emoji by 2 and moves it to the back of the enemy Squad",
  },
  {
    emoji: "🧲",
    id: 56,
    hp: 2,
    dmg: 2,
    rarity: 1,
    names: ["Magnet", "Attraction", "Sniper", "Snipe"],
    class: 4,
    description:
      "When defeated, damages the furthermost enemy Emoji by 2 and moves it to the front of the enemy Squad",
  },
  {
    emoji: "😷",
    id: 57,
    hp: 2,
    dmg: 1,
    rarity: 3, // Master of Transformation
    names: [
      "Mask",
      "Facemask",
      "Face Mask",
      "Face with Mask",
      "Coronavirus",
      "Covid",
      "Pandemic",
    ],
    class: 5,
    description:
      "When defeated, summons 🦠 at the front of the enemy Squad, and then Shuffles it",
  },
  {
    emoji: "🦠",
    id: 58,
    hp: 2,
    dmg: 1,
    rarity: -1,
    names: [
      "Microbe",
      "Virus",
      "Germ",
      "Bacteria",
      "Disease",
      "Sickness",
      "Illness",
      "Corruption",
      "Blight",
    ],
    description:
      "Before being Shuffled, transforms the Emoji behind it into a 🦠 with identical stats (summoned by 😷)",
  },
  {
    emoji: "🛸",
    id: 59,
    hp: 3,
    dmg: 2,
    rarity: 2,
    names: ["Flying Saucer", "Saucer", "Spaceship", "Ufo", "Aliens"],
    class: 6,
    description:
      "When defeated, Shuffle the enemy Squad and deal 3 damage to the frontmost enemy Emoji",
  },
  {
    emoji: "🪞",
    id: 60,
    hp: 5,
    dmg: 1,
    rarity: 3, // Master of Defense
    names: ["Mirror", "Window", "Glass", "Reflect", "Reflection"],
    class: 2,
    description:
      "Attacks for as much damage as the frontmost enemy Emoji, plus its own attack power",
  },
  {
    emoji: "🪄",
    id: 61,
    hp: 2,
    dmg: 1,
    rarity: 3, // Master of Summoning
    names: ["Magic Wand", "Wand", "Magic", "Spell", "Staff"],
    class: 3,
    description:
      "When the first friendly Emoji is defeated this round, revives it at 2 health at the back of the Squad, and defeats itself",
  },
  {
    emoji: "🏙️",
    id: 62,
    hp: 1,
    dmg: 1,
    rarity: 2,
    names: [
      "Cityscape",
      "City",
      "Skyline",
      "Town",
      "Skyscrapers",
      "Skyscraper",
      "Lilys",
    ],
    class: 8,
    description:
      "When a friendly Emoji dies, heals all friendly copies of it by 1",
  },
  {
    emoji: "🔊",
    id: 63,
    hp: 4,
    dmg: 0,
    rarity: 3, // Master of Musical
    names: [
      "Loud Sound",
      "Speaker",
      "Speakers",
      "Audio",
      "Loud",
      "Blast",
      "Amplifier",
      "Amplified",
    ],
    class: 7,
    description:
      "Attacks for as much damage as the number of friendly 🎶 ×2, plus its own attack power",
  },
  {
    emoji: "🍄",
    id: 64,
    hp: 6,
    dmg: 2,
    rarity: 0,
    names: ["Mushroom", "Red Mushroom", "Fungus", "Shroom"],
    class: 1,
    description: "After attacking, damages itself by 1",
  },
  {
    emoji: "👥",
    id: 65,
    hp: 2,
    dmg: 2,
    rarity: 1,
    names: [
      "Busts in Silhouette",
      "Busts",
      "Silhouette",
      "Silhouettes",
      "Shadows",
      "Shadow",
      "Shades",
      "Shade",
      "Mystery",
      "Mysterious",
      "Unknown",
    ],
    class: 3,
    description:
      "When defeated, replaces itself with an exact copy of the frontmost enemy Emoji",
  },
  {
    emoji: "🆕",
    id: 66,
    hp: 3,
    dmg: 1,
    rarity: 2,
    names: ["New", "New Button", "New Indicator"],
    class: 5,
    description:
      "When the friendly Emoji in front of this is defeated, restores that Emoji to original condition and defeats itself",
  },
  {
    emoji: "🔏",
    id: 67,
    hp: 4,
    dmg: 1,
    rarity: 2,
    names: [
      "Lock with Ink Pen",
      "Lock with Pen",
      "Locked with Pen",
      "Lock Pen",
      "Lock with Nib",
      "Ink Lock",
      "Lock Ink",
      "Pen Lock",
      "Lock Pen",
    ],
    class: 5,
    description:
      "When attacked, transforms the frontmost enemy emoji into a 🔒 with identical stats, and increases the frontmost enemy's attack power by 1",
  },
  {
    emoji: "🔒",
    id: 68,
    hp: null,
    dmg: null,
    rarity: -1,
    names: ["Lock", "Locked", "Padlock"],
    class: null,
    description: "Nothing Special (secured by 🔏)",
  },
  {
    emoji: "🏺",
    id: 69,
    hp: 1,
    dmg: 1,
    rarity: 1,
    names: ["Amphora", "Vase", "Pot", "Clay Pot", "Urn"],
    class: 5,
    description: "When defeated, summons a random *️⃣ Common emoji",
  },
  {
    emoji: "🛜",
    id: 70,
    hp: 3,
    dmg: 2,
    rarity: 0,
    names: [
      "Wireless",
      "Internet",
      "Network",
      "Signal",
      "Wifi",
      "Wi-fi",
      "Data",
      "Connection",
      "Rings",
    ],
    class: 8,
    description:
      "At the beginning of the Battle, increases its health by the number of friendly 🛜",
  },
  {
    emoji: "⚓",
    id: 71,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: ["Anchor"],
    class: 8,
    description:
      "When your Squad is Shuffled, this and the friendly Emoji in front of it do not get moved",
  },
  {
    emoji: "📌",
    id: 72,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: ["Pushpin", "Pin", "Thumbtack", "Tack"],
    class: 8,
    description:
      "When your Squad is Shuffled, this and the friendly Emoji behind it do not get moved",
  },
  {
    emoji: "🚧",
    id: 73,
    hp: 4,
    dmg: 1,
    rarity: 2,
    names: ["Construction", "Barrier", "Under Construction", "Traffic Barrier"],
    class: 8,
    description:
      "When your Squad is Shuffled, this does not get moved. Additionally, Emojis will not move past this during the shuffle",
  },
  {
    emoji: "🔋",
    id: 74,
    hp: 4,
    dmg: 0,
    rarity: 2,
    names: ["Battery", "Full Battery", "Charge"],
    class: 1,
    description:
      "Attacks for the amount of health it has, plus its own attack power",
  },
  {
    emoji: "💢",
    id: 75,
    hp: 2,
    dmg: 0,
    rarity: 1,
    names: ["Anger", "Anger Symbol", "Angry", "Backpack", "🎒"],
    class: 8,
    description:
      "The friendly Emoji in front of this attacks for 2 more damage",
  },
  {
    emoji: "🌫️",
    id: 76,
    hp: 0,
    dmg: 0,
    rarity: 1,
    names: ["Fog", "Mist", "Foggy", "Misty"],
    class: 0,
    description:
      "At the beginning of the Battle, heals the friendly Emoji in front of itself by 3 and defeats itself",
  },
  {
    emoji: "🎧",
    id: 77,
    hp: 4,
    dmg: 2,
    rarity: 0,
    names: ["Headphones", "Earbuds"],
    class: 7,
    description:
      "Friendly Emojis in front of this act as if this was a 🎶 emoji",
  },
  {
    emoji: "🎷",
    id: 78,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: ["Saxophone", "Sax"],
    class: 7,
    description:
      "If there is at least one undefeated friendly 🎶, heals the friendly Emoji in front of itself by 1 when it is attacked for more than 1 damage.",
  },
  {
    emoji: "🥁",
    id: 79,
    hp: 4,
    dmg: 3,
    rarity: 1,
    names: ["Drum", "Drum with Drumsticks"],
    class: 7,
    description:
      "If there is at least one undefeated friendly 🎶, takes 1 less damage from every attack to a minimum of 1",
  },
  {
    emoji: "📠",
    id: 80,
    hp: 2,
    dmg: 2,
    rarity: 2,
    names: ["Fax", "Fax Machine", "Receipt Printer", "Printer"],
    class: 3,
    description:
      "When this defeats an Emoji, it summons 📃 at the front of the Squad",
  },
  {
    emoji: "📃",
    id: 81,
    hp: 1,
    dmg: 1,
    rarity: -1,
    names: ["Page with Curl", "Page", "Wall Of Text"],
    class: null,
    description: "Nothing Special (printed by 📠)",
  },
  {
    emoji: "🕊️",
    id: 82,
    hp: 6,
    dmg: 3,
    rarity: 3,
    names: ["Dove", "Bird"],
    class: 4,
    description:
      "When this would defeat an Emoji, converts it to the friendly team and moves it to the front of the Squad with 1 health",
  },
  {
    emoji: "😇",
    id: 83,
    hp: 6,
    dmg: 3,
    rarity: 1,
    names: ["Innocent", "Halo", "Holy", "Angel Face", "Smiling Face with Halo"],
    class: 2,
    description: "When this defeats an Emoji, attacks itself for 3",
  },
  {
    emoji: "🏹",
    id: 84,
    hp: 4,
    dmg: 3,
    rarity: 1,
    names: ["Bow and Arrow", "Archery", "Bow", "Crossbow"],
    class: 1,
    description:
      "Attacks the Emoji behind the frontmost enemy Emoji, if possible",
  },
  {
    emoji: "💉",
    id: 85,
    hp: 0,
    dmg: 0,
    rarity: 1,
    names: ["Syringe", "Shot", "Steroids"],
    class: 1,
    description:
      "At the beginning of the Battle, increases the attack power of friendly Emoji in front of itself by 1 and defeats itself",
  },
  {
    emoji: "🦴",
    id: 86,
    hp: 2,
    dmg: 0,
    rarity: 1,
    names: ["Bone", "Fossil"],
    class: 5,
    description: "When this would be defeated, instead transforms into 🦖",
  },
  {
    emoji: "🦖",
    id: 87,
    hp: 5,
    dmg: 2,
    rarity: -1,
    names: ["T Rex", "Dinosaur", "Dino", "T-Rex", "Trex", "Rex"],
    class: null,
    description: "Nothing Special (evolved from 🦴)",
  },
  {
    emoji: "🔙",
    id: 88,
    hp: 3,
    dmg: 3,
    rarity: 1,
    names: ["Back", "Back Arrow", "Back Sign"],
    class: 1,
    description:
      "Attacks the Emoji at the back of the enemy Squad instead of the front",
  },
  {
    emoji: "🎯",
    id: 89,
    hp: 6,
    dmg: 1,
    rarity: 1,
    names: ["Dart", "Direct Hit", "Target", "Bullseye"],
    class: 2,
    description:
      "All enemy attacks are redirected towards this, regardless of the aggressor's position",
  },
  {
    emoji: "💰",
    id: 90,
    hp: 1,
    dmg: 0,
    rarity: -1,
    names: ["Moneybag", "Money Bag", "Marigold", "Sack"],
    class: null,
    description:
      "When this survives a Battle without being defeated, give you more money idk",
  },
  {
    emoji: "🚨",
    id: 91,
    hp: 2,
    dmg: 2,
    rarity: 0,
    names: ["Rotating Light", "Alarm", "Police Light", "Siren"],
    class: 3,
    description:
      "If this is the only undefeated friendly Emoji, summon 🚓 at the back of the Squad",
  },
  {
    emoji: "🚓",
    id: 92,
    hp: 3,
    dmg: 4,
    rarity: -1,
    names: ["Police Car", "Police", "Cop", "Cops", "Opps"],
    class: null,
    description: "Nothing Special (called in by 🚨)",
  },
  {
    emoji: "🐝",
    id: 93,
    hp: 2,
    dmg: 1,
    rarity: 0,
    names: ["Bee", "Bumblebee"],
    class: 8,
    description:
      "When attacking, all friendly 🐝 also attack regardless of position.",
  },
  {
    emoji: "🪡",
    id: 94,
    hp: 3,
    dmg: 3,
    rarity: 2,
    names: ["Sewing Needle", "Needle"],
    class: 1,
    description:
      "When attacking, attacks the first X emojis in the enemy Squad for 1 damage, where X is its attack power.",
  },
  {
    emoji: "👪",
    id: 95,
    hp: 2,
    dmg: 0,
    rarity: 3, // Master of Teamup
    names: ["Family"],
    class: 8,
    description:
      "At the beginning of the Battle, increases its health and attack power by the number of friendly Teamup class emojis",
  },
  {
    emoji: "🪗",
    id: 96,
    hp: 3,
    dmg: 3,
    rarity: 2,
    names: ["Accordion"],
    class: 7,
    description:
      "If there is at least one undefeated friendly 🎶, attacks the 2 frontmost enemy emojis at once",
  },
  {
    emoji: "🩹",
    id: 97,
    hp: 5,
    dmg: 2,
    rarity: 2,
    names: ["Adhesive Bandage", "Bandaid", "Bandage", "Band-aid"],
    class: 1,
    description: "Enemy Emojis directly in front of this cannot be healed",
  },
  {
    emoji: "🔇",
    id: 98,
    hp: 3,
    dmg: 2,
    rarity: 2,
    names: ["Mute", "Muted Speaker", "Muted", "Sound Off"],
    class: 7,
    description: "Enemy Emojis that benefit from 🎶 do not recieve their benefits",
  },
  {
    emoji: "🫨",
    id: 99,
    hp: 4,
    dmg: 2,
    rarity: 1,
    names: ["Shaking Face", "Shaking", "Vibrating Face", "Vibrating"],
    class: 6,
    description: "When your Squad is Shuffled, increases its attack power by 1",
  },
  {
    emoji: "🔍",
    id: 100,
    hp: 4,
    dmg: 1,
    rarity: 0,
    names: ["Mag", "Magnifying Glass", "Magnifying Glass Left", "Mag Left", "Mag 1", "🔎"],
    class: 1,
    description: "Targets the enemy Emoji with the least health",
  },
  {
    emoji: "🔝",
    id: 101,
    hp: 3,
    dmg: 3,
    rarity: 0,
    names: ["Top", "Top Arrow", "Dartichoke"],
    class: 1,
    description: "Targets the enemy Emoji with the most health",
  },
  {
    emoji: "🧦",
    id: 102,
    hp: 3,
    dmg: 1,
    rarity: 0,
    names: ["Socks", "Sock", "Thigh Highs", "Programming Socks", "Leg Warmers"],
    class: 1,
    description: "When attacking, attacks 2 consecutive times",
  },
  {
    emoji: "💐",
    id: 103,
    hp: 5,
    dmg: 1,
    rarity: 1,
    names: ["Bouquet", "Flowers"],
    class: 1,
    description: "When a friendly Emoji is defeated, increases its attack power by 1",
  },
  {
    emoji: "⛄",
    id: 104,
    hp: 2,
    dmg: 1,
    rarity: 0,
    names: ["Snowman", "Snowman without Snow"],
    class: 6,
    description: "When your Squad is shuffled, Emojis retain their positions and this defeats itself",
  },
  {
    emoji: "🪨",
    id: 105,
    hp: 7,
    dmg: 1,
    rarity: 0,
    names: ["Rock", "Stone", "Boulder"],
    class: 6,
    description: "when shuffle rock dont move",
  },
  {
    emoji: "📡",
    id: 106,
    hp: 2,
    dmg: 2,
    rarity: 1,
    names: ["Satellite", "Satellite Dish", "Dish", "Reciever Dish", "Antenna"],
    class: 8,
    description: "When the friendly frontmost Emoji is healed, this heals the same amount",
  },
  {
    emoji: "⏮️",
    id: 107,
    hp: 5,
    dmg: 2,
    rarity: 0,
    names: [
      "Track Previous",
      "Previous Track",
      "Previous Track Button",
      "Previous",
      "Track Last",
      "Last Track",
      "Last Track Button",
      "Last",
    ],
    class: 6,
    description: "When attacked or defeated, Shuffles your Squad",
  },
  {
    emoji: "❤️‍🔥",
    id: 108,
    hp: 3,
    dmg: 2,
    rarity: 1,
    names: [
      "Heart on Fire",
      "Flaming Heart",
      "Fire Heart",
      "Red Heart on Fire",
    ],
    class: 1,
    description: "When healed, damages the frontmost enemy Emoji for as much healing it received",
  },
  {
    emoji: "🥊",
    id: 109,
    hp: 5,
    dmg: 2,
    rarity: 0,
    names: [
      "Boxing Glove",
      "Boxing",
      "Punching Glove",
    ],
    class: 1,
    description: "Deals 1 more damage if the frontmost enemy Emoji has more health than it",
  },
  {
    emoji: "🥌",
    id: 109,
    hp: 4,
    dmg: 2,
    rarity: 0,
    names: [
      "Curling Stone",
      "Curling",
      "Curl",
    ],
    class: 1,
    description: "When attacked, switches places with the friendly Emoji behind it and the new frontmost friendly Emoji attacks once",
  },
];

module.exports = {
  healthemojis,
  dmgemojis,
  raritycolors,
  devotionhelp,
  classes,
  emojis,
  raritysymbols,
  raritynames,
};
